Repository OxfordIHTM/ihtm-hackathon-2023, pull requests merged in 2023-03, with the labels that each got.

#9 Ruchi
  coverage_assessment.R
Labels: analysis

#11 add code by team @OxfordIHTM/squirtle
  coverage_assessment.R
  coverage_assessment_report.Rmd
Labels: analysis

#12 update workflow
  .github/workflows/deploy-workflow.yml
  coverage_assessment.R
Labels: testing

#13 update deploy workflow
  .github/workflows/deploy-workflow.yml
  coverage_assessment.R
Labels: testing

#14 Prefinal
  .github/workflows/deploy-workflow.yml
  coverage_assessment.R
  coverage_assessment_report.Rmd
Labels: analysis

#16 update README
  README.Rmd
  README.md
  coverage_assessment_report.Rmd
Labels: documentation

#17 update workflow
  .github/workflows/check-workflow.yml
Labels: testing

#18 update README and report
  README.Rmd
  README.md
  coverage_assessment_report.Rmd
Labels: documentation

#19 check spellings in report
  coverage_assessment.R
  coverage_assessment_report.Rmd
Labels: documentation
